server:
  port: 8080

spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:sql/tables_hsqldb.sql'
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver 
    platform: hsqldb
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        type: trace
        use_sql_comments: true
        format_sql: true 
        cache.use_second_level_cache: false 
        cache.use_query_cache: false
        generate_statistics: false
        cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

org:
    quartz:
        scheduler:
            instanceId: AUTO
            instanceName: kingbbode-example
            makeSchedulerThreadDaemon : true
            interruptJobsOnShutdown  : true
        jobStore:
            clusterCheckinInterval: 20000
            driverDelegateClass: org.quartz.impl.jdbcjobstore.HSQLDBDelegate
            isClustered: true
            misfireThreshold: 60000
            tablePrefix: QRTZ_
            useProperties: false
        threadPool:
            threadCount: 5
            makeThreadsDaemons : true         